name: Build docker image and push to DockerHub.
# - How to Run Python Scripts in GitHub Action Workflows, Data Engineering With Nick, 1.43K subscribers
#   https://www.youtube.com/watch?v=zk4bSTD8uWM

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
      # selected-environment:
          # type: environment
          # description: Select the environment.

jobs:
  pre-action-step:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4
      - name: Print selected-environment.
        run: | 
          # echo "Environment selected is ${{ inputs.selected-environment }}."
          echo ""
  
  build-and-push-image-to-docker-hub:
    needs: [pre-action-step]
    environment: "production"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4

      - name: Login to Docker Hub.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Docker Hub.
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest
