# Note the deployed model should have /info that shows the change log and version number.
# Commit your changes and push them. Then we will tag our release with the v0.0.1 release:
# git add .
# git commit -m "created info endpoint"
# git push
# git tag "v0.0.1"
# This will trigger the deploy.yml.
# git push origin v0.0.1

name: Deploy the release version of the model(s) to staging and production.

on:
  push:
    branches:
      - xxx_main_xxx
    tags:
      # - 'v*.*.*'
      # Push events to match v*, i.e. v1.0, v20.15.10.
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push-image-to-docker-hub:
    environment: "production"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Get release version.
        # $RELEASE_VERSION is blank.
        # $GITHUB_REF_NAME = v1.0.5
        # ${{ github.ref_name }} = v1.0.5
        # ${{ github.ref }} = refs/tags/v1.0.5
        # ${{ github.event.release.tag_name }} is blank.
        # $GIT_TAG = v1.0.5???
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
      - run: |
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
      - run: |
          echo "github.ref: ${{ github.ref }}"
      - run: |
          echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"
      - run: |
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
          echo $GIT_TAG

      - name: Login to Docker Hub.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Docker Hub.
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.ref }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.ref_name }}

  deploy:
    name: Release
    needs: [build-and-push-image-to-docker-hub]
    environment: "production"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4
      # - name: Download model???
        # uses: actions/download-artifact@v2
        # with:
          # name: api
      - run: |
          echo "Deploy infrastructures using Terraform..."
