name: Run Python script to prepare the dataset for training
# - How to Run Python Scripts in GitHub Action Workflows, Data Engineering With Nick, 1.43K subscribers
#   https://www.youtube.com/watch?v=zk4bSTD8uWM

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository.
        uses: actions/checkout@v3

      - name: Setup Python 3.12.
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install Python Dependencies.
        run: |
          # python -m pip install --upgrade . botocore boto3 awscli
          echo "Install Python Dependencies."
          python -m pip install --upgrade

      - name: Run python prepare/prepare.py.
        run: |
          echo "Run python prepare/prepare.py."
          python prepare/prepare.py

  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python Dependencies.
        run: |
          echo "Install Python Dependencies."
          python -m pip install --upgrade

      - name: Train And Build Model.
        run: |
          echo "Run python train_build/train_build.py."
          python train_build/train_build.py
